import Colors from "./Colors";
import Car from "./exercise1";
import Directions from "./Directions";
import Doors from "./Doors";

const sandero = new Car('Renault', Colors.SILVER, 4);

sandero.openTheDoor(Doors.DRIVER);
sandero.closeTheDoor(Doors.DRIVER);
sandero.turnOn();
sandero.speedUp();
sandero.speedDown();
sandero.turn(Directions.LEFT);
sandero.speedUp();
sandero.speedDown();
sandero.turn(Directions.RIGHT);
sandero.speedUp();
sandero.speedDown();
sandero.turn(Directions.RIGHT);
sandero.speedUp();
sandero.speedDown();
sandero.stop();
sandero.openTheDoor(Doors.BEHIND_PASSENGER);
sandero.closeTheDoor(Doors.BEHIND_PASSENGER);
sandero.speedUp();
sandero.speedDown();
sandero.turn(Directions.RIGHT);
sandero.speedUp();
sandero.speedDown();
sandero.turn(Directions.LEFT);
sandero.speedUp();
sandero.speedDown();
sandero.turn(Directions.RIGHT);
sandero.speedUp();
sandero.speedDown();
sandero.stop();
sandero.openTheDoor(Doors.BEHIND_PASSENGER);
sandero.closeTheDoor(Doors.BEHIND_PASSENGER);
sandero.speedUp();