"use strict";
exports.__esModule = true;
var Colors_1 = require("./Colors");
var exercise1_1 = require("./exercise1");
var Directions_1 = require("./Directions");
var Doors_1 = require("./Doors");
var sandero = new exercise1_1["default"]('Renault', Colors_1["default"].SILVER, 4);
sandero.openTheDoor(Doors_1["default"].DRIVER);
sandero.closeTheDoor(Doors_1["default"].DRIVER);
sandero.turnOn();
sandero.speedUp();
sandero.speedDown();
sandero.turn(Directions_1["default"].LEFT);
sandero.speedUp();
sandero.speedDown();
sandero.turn(Directions_1["default"].RIGHT);
sandero.speedUp();
sandero.speedDown();
sandero.turn(Directions_1["default"].RIGHT);
sandero.speedUp();
sandero.speedDown();
sandero.stop();
sandero.openTheDoor(Doors_1["default"].BEHIND_PASSENGER);
sandero.closeTheDoor(Doors_1["default"].BEHIND_PASSENGER);
sandero.speedUp();
sandero.speedDown();
sandero.turn(Directions_1["default"].RIGHT);
sandero.speedUp();
sandero.speedDown();
sandero.turn(Directions_1["default"].LEFT);
sandero.speedUp();
sandero.speedDown();
sandero.turn(Directions_1["default"].RIGHT);
sandero.speedUp();
sandero.speedDown();
sandero.stop();
sandero.openTheDoor(Doors_1["default"].BEHIND_PASSENGER);
sandero.closeTheDoor(Doors_1["default"].BEHIND_PASSENGER);
sandero.speedUp();
